### ISSUE TITLE
when `to png` 0.4.2 is used inside of custom commands it creates files inside of `cargo/bin`

### ISSUE THREAD

**Issue by maxim-uvarov** [FMotalleb/nu_plugin_image#14]
when `to png` 0.4.2 is used inside of custom commands it creates files inside of `cargo/bin`. 

I can found some details of solution here: https://github.com/nushell/nushell/issues/12660#issuecomment-2077118521

You can reproduce this:

```
def test_png [] {table | to png 'test.png'}
ls | test_png
```

![image](https://github.com/FMotalleb/nu_plugin_image/assets/4896754/90f2ab45-5865-4dbf-ba46-eecc897c5ab6)

**Comment by FMotalleb** [comment]
![image](https://github.com/FMotalleb/nu_plugin_image/assets/30149519/5b8a24b5-9847-45e5-abd9-0ee269c13dcf)
