### ISSUE TITLE
error in 0.97.2

### ISSUE THREAD

**Issue by kurokirasama** [FMotalleb/nu_plugin_image#18]
Hey, I just updated nushell to 0.97.2 and the plugin to 0.5.4, but when doing `plugin add ~/.cargo/bin/nu_plugin_port_scan` i get this error:

```
Error: nu::shell::plugin_failed_to_decode

  × Plugin failed to decode: missing field `description`
```

**Comment by FMotalleb** [comment]
Duplicate of https://github.com/FMotalleb/nu_plugin_port_scan/issues/3#
